@echo off
REM =============================================================================
REM res_web - LOCAL BUILD for Docker Container Testing
REM =============================================================================
REM This script builds the static export with LOCAL Docker API URLs
REM Run this when you want to test the built static site against local backend
REM =============================================================================

echo ================================================================================
echo res_web - Local Build (Docker Container Testing)
echo ================================================================================
echo.

REM Define local environment values
set "LOCAL_BASE_URL=http://localhost:3003"
set "LOCAL_API_URL=http://localhost:8000"

echo [1/4] Creating .env.local with LOCAL Docker values...
echo.

REM Dynamically create .env.local with local values
(
echo # =============================================================================
echo # res_web Frontend - LOCAL BUILD Configuration
echo # =============================================================================
echo # AUTO-GENERATED by build_local.bat - DO NOT EDIT MANUALLY
echo # For local Docker container testing
echo # =============================================================================
echo.
echo # Frontend Base URL ^(Local^)
echo NEXT_PUBLIC_BASE_URL=%LOCAL_BASE_URL%
echo.
echo # Backend API URL ^(Local Docker Container^)
echo NEXT_PUBLIC_API_URL=%LOCAL_API_URL%
) > .env.local

echo Created .env.local with:
echo   NEXT_PUBLIC_BASE_URL=%LOCAL_BASE_URL%
echo   NEXT_PUBLIC_API_URL=%LOCAL_API_URL%
echo.

echo [2/4] Cleaning previous build...
if exist out rmdir /s /q out >nul 2>&1
if exist .next rmdir /s /q .next >nul 2>&1
echo Cleaned build directories
echo.

echo [3/4] Building static export...
call npm run build
if errorlevel 1 (
    echo.
    echo ================================================================================
    echo ERROR: Build failed!
    echo ================================================================================
    pause
    exit /b 1
)
echo.

echo [4/4] Build complete!
echo.

echo ================================================================================
echo SUCCESS! Local build complete
echo ================================================================================
echo.
echo Static files are in the 'out' folder
echo.
echo Baked-in values:
echo   Base URL: %LOCAL_BASE_URL%
echo   API URL:  %LOCAL_API_URL%
echo.

echo ================================================================================
echo [5/5] Starting Next.js dev server on port 3003 (hot reload enabled)...
echo ================================================================================
echo.
echo Make sure backend is running: cd ..\res_backend ^&^& run_docker_sync.bat
echo.
echo Press Ctrl+C to stop the server
echo.
npm run dev
