"""
Engineer Profile Configuration for the Fit Check Agent.

This module is AUTO-GENERATED from the profile/ directory (Single Point of Truth).
DO NOT EDIT THIS FILE DIRECTLY. Edit the JSON files in profile/ instead.

Source: scripts/generate-profile-config.py
Generated from: profile/*.json

This module contains the engineer's skills, experience, and background
information used by the AI agent to match against employer requirements.
"""

from typing import Dict, List, Any


# =============================================================================
# Engineer Profile Data (AUTO-GENERATED)
# =============================================================================

ENGINEER_PROFILE: Dict[str, Any] = {
    "name": "Software Engineer",
    "education": "Bachelor of Science Degree in Computer Science",
    "skills": {
        "languages": [
            "Python",
            "JavaScript",
            "TypeScript",
            "Dart",
            "Lua",
            "Java",
            "SQL",
            "HTML/CSS",
        ],
        "frameworks": [
            "Flutter",
            "React",
            "Next.js",
            "Vite",
            "FastAPI",
            "Node.js",
            "TailwindCSS",
            "Radix UI",
            "Shadcn UI",
        ],
        "cloud_devops": [
            "Docker",
            "Firebase",
            "MongoDB",
            "PostgreSQL",
            "Redis",
            "PayPal Integration",
            "CI/CD",
        ],
        "ai_ml": [
            "LangChain",
            "LangGraph",
            "LangSmith",
            "OpenAI API",
            "Google Gemini",
            "RAG Systems",
            "MCP Servers",
            "Prompt Engineering",
            "Vector Stores",
        ],
        "tools": [
            "Git",
            "GitHub",
            "VS Code",
            "Overwolf SDK",
            "Linux",
            "REST APIs",
        ],
    },
    "experience_summary": """
Full-stack software engineer and December 2025 CSU Sacramento graduate specializing in AI-powered applications and agentic systems. Experienced in building production platforms from concept to client delivery.

Key accomplishments:
- Delivered ChurchLink platform to production—a Web & App Builder with localization and payment processing for a real church client
- Built a Deep Researcher Agent using LangGraph and Google CSE for graph-based web research orchestration
- Created Zharvis, an Overwolf gaming overlay SaaS with RAG pipelines processing 15k+ wiki documents
- First profitable SaaS at age 19, generating $6k revenue with a team of 3 developers
- Self-taught foundation starting with first GitHub commit at age 15
    """,
    "notable_projects": [
        {
            "name": "Interactive Portfolio with Deep Researcher",
            "description": "AI-powered portfolio that analyzes employer fit through comparative research against job descriptions",
            "tech": [
                "Next.js",
                "Shadcn UI",
                "Python",
                "FastAPI",
                "LangGraph",
                "Docker",
            ],
        },
        {
            "name": "ChurchLink Platform",
            "description": "Full-stack church management system with cross-platform apps, localization, and payment integration",
            "tech": [
                "Flutter",
                "TypeScript",
                "FastAPI",
                "Firebase",
                "MongoDB",
                "PayPal",
            ],
        },
        {
            "name": "Zharvis Gaming Assistant",
            "description": "Overwolf overlay providing AI-powered in-game assistance with RAG document retrieval",
            "tech": [
                "Overwolf SDK",
                "LangChain",
                "MCP",
                "Vector Stores",
                "Python",
            ],
        },
    ],
    "strengths": [
        "Rapid learner who quickly adapts to new technologies and frameworks",
        "Hands-on experience shipping production software to real clients",
        "Deep expertise in AI/ML tooling including LangChain, LangGraph, and RAG systems",
        "Full-stack capabilities spanning Flutter, React, FastAPI, and cloud infrastructure",
        "Entrepreneurial mindset with proven ability to generate revenue from software products",
    ],
    "career_interests": [
        "AI/ML Engineering & Agentic Systems",
        "Full-Stack Development",
        "Backend Systems & APIs",
        "Developer Tools & Productivity",
        "Gaming & Interactive Applications",
    ],
}


# =============================================================================
# Profile Formatting Functions
# =============================================================================

def get_formatted_profile() -> str:
    """
    Format engineer profile for system prompt injection.
    
    Returns:
        str: Formatted string representation of the engineer profile
             suitable for inclusion in AI system prompts.
    """
    profile = ENGINEER_PROFILE
    
    # Format skills by category
    skills_formatted = []
    for category, skill_list in profile["skills"].items():
        category_name = category.replace("_", " ").title()
        skills_str = ", ".join(skill_list)
        skills_formatted.append(f"  {category_name}: {skills_str}")
    
    # Format projects
    projects_formatted = []
    for project in profile["notable_projects"]:
        tech_str = ", ".join(project["tech"])
        projects_formatted.append(
            f"  - {project['name']}: {project['description']} "
            f"(Tech: {tech_str})"
        )
    
    # Build the formatted profile string
    return f"""
Name: {profile['name']}
Education: {profile['education']}

Technical Skills:
{chr(10).join(skills_formatted)}

Experience Summary:
{profile['experience_summary'].strip()}

Notable Projects:
{chr(10).join(projects_formatted)}

Key Strengths:
{chr(10).join(f"  - {s}" for s in profile['strengths'])}

Career Interests:
{chr(10).join(f"  - {i}" for i in profile['career_interests'])}
""".strip()


def get_skills_by_category() -> Dict[str, List[str]]:
    """
    Get all skills organized by category.
    
    Returns:
        Dict[str, List[str]]: Skills grouped by category
                             (languages, frameworks, cloud_devops, ai_ml, tools)
    """
    return ENGINEER_PROFILE["skills"]


def get_skills_list() -> List[str]:
    """
    Get a flat list of all skills across all categories.
    
    Returns:
        List[str]: Flat list of all skill names
    """
    all_skills = []
    for skill_list in ENGINEER_PROFILE["skills"].values():
        all_skills.extend(skill_list)
    return all_skills


def get_experience_summary() -> str:
    """
    Get the engineer's experience summary.
    
    Returns:
        str: Multi-line experience summary text
    """
    return ENGINEER_PROFILE["experience_summary"]


def get_projects() -> List[Dict[str, Any]]:
    """
    Get the list of notable projects.
    
    Returns:
        List[Dict[str, Any]]: List of project dictionaries with name, description, tech
    """
    return ENGINEER_PROFILE["notable_projects"]


def get_strengths() -> List[str]:
    """
    Get the engineer's key strengths.
    
    Returns:
        List[str]: List of strength statements
    """
    return ENGINEER_PROFILE["strengths"]


def get_career_interests() -> List[str]:
    """
    Get the engineer's career interests.
    
    Returns:
        List[str]: List of career interest areas
    """
    return ENGINEER_PROFILE["career_interests"]


# =============================================================================
# Profile Metadata (for reference)
# =============================================================================

# This module was generated from the following source files:
# - profile/identity.json
# - profile/skills.json
# - profile/projects.json
# - profile/education.json
# - profile/contact.json
# - profile/assets.json
# - profile/site_metadata.json
# - profile/ai_models.json
# - profile/pipeline_phases.json
# - profile/experience.json
#
# To update this module, edit the JSON files and run:
#     python scripts/generate-profile-config.py
