"""
Engineer Profile Configuration for the Fit Check Agent.

This module is AUTO-GENERATED from the profile/ directory (Single Point of Truth).
DO NOT EDIT THIS FILE DIRECTLY. Edit the JSON files in profile/ instead.

Source: scripts/generate-profile-config.py
Generated from: profile/*.json

This module contains the engineer's skills, experience, and background
information used by the AI agent to match against employer requirements.
"""

from typing import Dict, List, Any


# =============================================================================
# Engineer Profile Data (AUTO-GENERATED)
# =============================================================================

ENGINEER_PROFILE: Dict[str, Any] = {
    "name": "Software Engineer",
    "education": "Bachelor of Science Degree in Computer Science",
    "skills": {
        "languages": [
            "Python",
            "JavaScript",
            "TypeScript",
            "SQL",
            "HTML/CSS",
        ],
        "frameworks": [
            "React",
            "Next.js",
            "FastAPI",
            "Node.js",
            "TailwindCSS",
        ],
        "cloud_devops": [
            "Docker",
            "AWS",
            "PostgreSQL",
            "Redis",
            "CI/CD",
        ],
        "ai_ml": [
            "LangChain",
            "LangGraph",
            "OpenAI API",
            "Google Gemini",
            "RAG Systems",
            "Prompt Engineering",
        ],
        "tools": [
            "Git",
            "VS Code",
            "Linux",
            "REST APIs",
            "GraphQL",
        ],
    },
    "experience_summary": """
Full-stack software engineer with experience building modern web applications and AI-powered systems. Proficient in developing scalable backend services, responsive frontend interfaces, and integrating cutting-edge AI/ML capabilities.

Key accomplishments:
- Built production AI agents using LangChain and LangGraph
- Developed full-stack applications with React/Next.js and FastAPI
- Implemented real-time streaming features using SSE and WebSockets
- Designed and deployed containerized microservices architecture
- Created RAG systems for intelligent document processing
    """,
    "notable_projects": [
        {
            "name": "AI Portfolio Assistant",
            "description": "Real-time AI agent that analyzes employer fit using web research and skill matching",
            "tech": [
                "Python",
                "FastAPI",
                "LangGraph",
                "React",
                "SSE Streaming",
            ],
        },
        {
            "name": "Full-Stack Web Platform",
            "description": "Production web application with authentication, real-time features, and cloud deployment",
            "tech": [
                "Next.js",
                "FastAPI",
                "PostgreSQL",
                "Docker",
                "AWS",
            ],
        },
        {
            "name": "RAG Document System",
            "description": "Intelligent document retrieval and question-answering system",
            "tech": [
                "LangChain",
                "Vector Databases",
                "OpenAI",
                "Python",
            ],
        },
    ],
    "strengths": [
        "Fast learner who quickly adapts to new technologies",
        "Strong problem-solving and debugging skills",
        "Experience with end-to-end software development lifecycle",
        "Excellent communication and collaboration abilities",
        "Passionate about building AI-powered applications",
    ],
    "career_interests": [
        "Full-Stack Development",
        "AI/ML Engineering",
        "Backend Systems",
        "Cloud Architecture",
        "Developer Tools",
    ],
}


# =============================================================================
# Profile Formatting Functions
# =============================================================================

def get_formatted_profile() -> str:
    """
    Format engineer profile for system prompt injection.
    
    Returns:
        str: Formatted string representation of the engineer profile
             suitable for inclusion in AI system prompts.
    """
    profile = ENGINEER_PROFILE
    
    # Format skills by category
    skills_formatted = []
    for category, skill_list in profile["skills"].items():
        category_name = category.replace("_", " ").title()
        skills_str = ", ".join(skill_list)
        skills_formatted.append(f"  {category_name}: {skills_str}")
    
    # Format projects
    projects_formatted = []
    for project in profile["notable_projects"]:
        tech_str = ", ".join(project["tech"])
        projects_formatted.append(
            f"  - {project['name']}: {project['description']} "
            f"(Tech: {tech_str})"
        )
    
    # Build the formatted profile string
    return f"""
Name: {profile['name']}
Education: {profile['education']}

Technical Skills:
{chr(10).join(skills_formatted)}

Experience Summary:
{profile['experience_summary'].strip()}

Notable Projects:
{chr(10).join(projects_formatted)}

Key Strengths:
{chr(10).join(f"  - {s}" for s in profile['strengths'])}

Career Interests:
{chr(10).join(f"  - {i}" for i in profile['career_interests'])}
""".strip()


def get_skills_by_category() -> Dict[str, List[str]]:
    """
    Get all skills organized by category.
    
    Returns:
        Dict[str, List[str]]: Skills grouped by category
                             (languages, frameworks, cloud_devops, ai_ml, tools)
    """
    return ENGINEER_PROFILE["skills"]


def get_skills_list() -> List[str]:
    """
    Get a flat list of all skills across all categories.
    
    Returns:
        List[str]: Flat list of all skill names
    """
    all_skills = []
    for skill_list in ENGINEER_PROFILE["skills"].values():
        all_skills.extend(skill_list)
    return all_skills


def get_experience_summary() -> str:
    """
    Get the engineer's experience summary.
    
    Returns:
        str: Multi-line experience summary text
    """
    return ENGINEER_PROFILE["experience_summary"]


def get_projects() -> List[Dict[str, Any]]:
    """
    Get the list of notable projects.
    
    Returns:
        List[Dict[str, Any]]: List of project dictionaries with name, description, tech
    """
    return ENGINEER_PROFILE["notable_projects"]


def get_strengths() -> List[str]:
    """
    Get the engineer's key strengths.
    
    Returns:
        List[str]: List of strength statements
    """
    return ENGINEER_PROFILE["strengths"]


def get_career_interests() -> List[str]:
    """
    Get the engineer's career interests.
    
    Returns:
        List[str]: List of career interest areas
    """
    return ENGINEER_PROFILE["career_interests"]


# =============================================================================
# Profile Metadata (for reference)
# =============================================================================

# This module was generated from the following source files:
# - profile/identity.json
# - profile/skills.json
# - profile/projects.json
# - profile/education.json
# - profile/contact.json
# - profile/assets.json
# - profile/site_metadata.json
# - profile/ai_models.json
# - profile/pipeline_phases.json
# - profile/experience.json
#
# To update this module, edit the JSON files and run:
#     python scripts/generate-profile-config.py
