#!/usr/bin/env python3
"""
SPOT Profile Configuration Generator for Backend.

This script reads JSON files from the profile/ directory (Single Point of Truth)
and generates the backend/config/engineer_profile.py module.

Maintains backward compatibility with existing code while centralizing
configuration data for easier maintenance.

Usage:
    python scripts/generate-profile-config.py
"""

import json
import os
from pathlib import Path
from typing import Dict, Any, List


# =============================================================================
# Configuration
# =============================================================================

WORKSPACE_ROOT = Path(__file__).parent.parent
PROFILE_DIR = WORKSPACE_ROOT / "profile"
OUTPUT_FILE = WORKSPACE_ROOT / "backend" / "config" / "engineer_profile.py"


# =============================================================================
# JSON Loaders
# =============================================================================

def load_json(filename: str) -> Dict[str, Any]:
    """Load and parse a JSON file from the profile directory."""
    file_path = PROFILE_DIR / filename
    if not file_path.exists():
        raise FileNotFoundError(f"Required profile file not found: {filename}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def load_all_profile_data() -> Dict[str, Any]:
    """Load all profile JSON files."""
    return {
        'identity': load_json('identity.json'),
        'skills': load_json('skills.json'),
        'projects': load_json('projects.json'),
        'education': load_json('education.json'),
        'contact': load_json('contact.json'),
        'assets': load_json('assets.json'),
        'site_metadata': load_json('site_metadata.json'),
        'ai_models': load_json('ai_models.json'),
        'pipeline_phases': load_json('pipeline_phases.json'),
        'experience': load_json('experience.json'),
    }


# =============================================================================
# Code Generation
# =============================================================================

def format_python_dict(data: Any, indent: int = 0) -> str:
    """Format a Python dict with proper indentation."""
    indent_str = "    " * indent
    next_indent_str = "    " * (indent + 1)
    
    if isinstance(data, dict):
        if not data:
            return "{}"
        lines = ["{"]
        for key, value in data.items():
            formatted_value = format_python_dict(value, indent + 1)
            lines.append(f'{next_indent_str}"{key}": {formatted_value},')
        lines.append(f"{indent_str}}}")
        return "\n".join(lines)
    
    elif isinstance(data, list):
        if not data:
            return "[]"
        if all(isinstance(item, str) for item in data):
            # Inline string lists
            formatted_items = [f'"{item}"' for item in data]
            return "[\n" + "\n".join(f"{next_indent_str}{item}," for item in formatted_items) + f"\n{indent_str}]"
        else:
            # Complex lists
            lines = ["["]
            for item in data:
                formatted_item = format_python_dict(item, indent + 1)
                lines.append(f"{next_indent_str}{formatted_item},")
            lines.append(f"{indent_str}]")
            return "\n".join(lines)
    
    elif isinstance(data, str):
        # Handle multi-line strings
        if "\n" in data:
            return '"""\n' + data.strip() + '\n' + indent_str + '"""'
        return f'"{data}"'
    
    elif isinstance(data, (int, float, bool)) or data is None:
        return str(data)
    
    return repr(data)


def generate_engineer_profile_module(profile_data: Dict[str, Any]) -> str:
    """Generate the complete engineer_profile.py module."""
    
    identity = profile_data['identity']
    skills = profile_data['skills']
    projects = profile_data['projects']
    education = profile_data['education']
    
    # Build ENGINEER_PROFILE dict
    engineer_profile = {
        "name": identity['name']['professional_title'],
        "education": education['primary']['degree'],
        "skills": skills['backend_categories'],
        "experience_summary": identity['experience_summary'],
        "notable_projects": projects['backend_projects'],
        "strengths": identity['strengths'],
        "career_interests": identity['career_interests'],
    }
    
    # Format the profile dict
    profile_dict_str = format_python_dict(engineer_profile, indent=0)
    
    # Generate the complete module
    module_content = f'''"""
Engineer Profile Configuration for the Fit Check Agent.

This module is AUTO-GENERATED from the profile/ directory (Single Point of Truth).
DO NOT EDIT THIS FILE DIRECTLY. Edit the JSON files in profile/ instead.

Source: scripts/generate-profile-config.py
Generated from: profile/*.json

This module contains the engineer's skills, experience, and background
information used by the AI agent to match against employer requirements.
"""

from typing import Dict, List, Any


# =============================================================================
# Engineer Profile Data (AUTO-GENERATED)
# =============================================================================

ENGINEER_PROFILE: Dict[str, Any] = {profile_dict_str}


# =============================================================================
# Profile Formatting Functions
# =============================================================================

def get_formatted_profile() -> str:
    """
    Format engineer profile for system prompt injection.
    
    Returns:
        str: Formatted string representation of the engineer profile
             suitable for inclusion in AI system prompts.
    """
    profile = ENGINEER_PROFILE
    
    # Format skills by category
    skills_formatted = []
    for category, skill_list in profile["skills"].items():
        category_name = category.replace("_", " ").title()
        skills_str = ", ".join(skill_list)
        skills_formatted.append(f"  {{category_name}}: {{skills_str}}")
    
    # Format projects
    projects_formatted = []
    for project in profile["notable_projects"]:
        tech_str = ", ".join(project["tech"])
        projects_formatted.append(
            f"  - {{project['name']}}: {{project['description']}} "
            f"(Tech: {{tech_str}})"
        )
    
    # Build the formatted profile string
    return f"""
Name: {{profile['name']}}
Education: {{profile['education']}}

Technical Skills:
{{chr(10).join(skills_formatted)}}

Experience Summary:
{{profile['experience_summary'].strip()}}

Notable Projects:
{{chr(10).join(projects_formatted)}}

Key Strengths:
{{chr(10).join(f"  - {{s}}" for s in profile['strengths'])}}

Career Interests:
{{chr(10).join(f"  - {{i}}" for i in profile['career_interests'])}}
""".strip()


def get_skills_by_category() -> Dict[str, List[str]]:
    """
    Get all skills organized by category.
    
    Returns:
        Dict[str, List[str]]: Skills grouped by category
                             (languages, frameworks, cloud_devops, ai_ml, tools)
    """
    return ENGINEER_PROFILE["skills"]


def get_skills_list() -> List[str]:
    """
    Get a flat list of all skills across all categories.
    
    Returns:
        List[str]: Flat list of all skill names
    """
    all_skills = []
    for skill_list in ENGINEER_PROFILE["skills"].values():
        all_skills.extend(skill_list)
    return all_skills


def get_experience_summary() -> str:
    """
    Get the engineer's experience summary.
    
    Returns:
        str: Multi-line experience summary text
    """
    return ENGINEER_PROFILE["experience_summary"]


def get_projects() -> List[Dict[str, Any]]:
    """
    Get the list of notable projects.
    
    Returns:
        List[Dict[str, Any]]: List of project dictionaries with name, description, tech
    """
    return ENGINEER_PROFILE["notable_projects"]


def get_strengths() -> List[str]:
    """
    Get the engineer's key strengths.
    
    Returns:
        List[str]: List of strength statements
    """
    return ENGINEER_PROFILE["strengths"]


def get_career_interests() -> List[str]:
    """
    Get the engineer's career interests.
    
    Returns:
        List[str]: List of career interest areas
    """
    return ENGINEER_PROFILE["career_interests"]


# =============================================================================
# Profile Metadata (for reference)
# =============================================================================

# This module was generated from the following source files:
# - profile/identity.json
# - profile/skills.json
# - profile/projects.json
# - profile/education.json
# - profile/contact.json
# - profile/assets.json
# - profile/site_metadata.json
# - profile/ai_models.json
# - profile/pipeline_phases.json
# - profile/experience.json
#
# To update this module, edit the JSON files and run:
#     python scripts/generate-profile-config.py
'''
    
    return module_content


# =============================================================================
# Main Execution
# =============================================================================

def main():
    """Generate the engineer_profile.py module from SPOT JSON files."""
    print("=" * 70)
    print("SPOT Profile Configuration Generator - Backend")
    print("=" * 70)
    print()
    
    # Load all profile data
    print(f"📂 Loading profile data from: {PROFILE_DIR}")
    try:
        profile_data = load_all_profile_data()
        print(f"✅ Successfully loaded {len(profile_data)} profile files")
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        return 1
    except json.JSONDecodeError as e:
        print(f"❌ JSON parsing error: {e}")
        return 1
    
    # Generate the module
    print(f"\n🔧 Generating engineer_profile.py module...")
    try:
        module_content = generate_engineer_profile_module(profile_data)
    except Exception as e:
        print(f"❌ Generation error: {e}")
        return 1
    
    # Write to file
    print(f"💾 Writing to: {OUTPUT_FILE}")
    try:
        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(module_content)
        print(f"✅ Successfully generated backend config")
    except Exception as e:
        print(f"❌ Write error: {e}")
        return 1
    
    print()
    print("=" * 70)
    print("✨ Backend configuration generated successfully!")
    print("=" * 70)
    return 0


if __name__ == "__main__":
    exit(main())
