import { 
  Wifi, 
  Search, 
  Scale, 
  Briefcase, 
  FileCheck2, 
  CheckCircle2, 
  Database,
  Gauge,
  Brain
} from 'lucide-react';

/**
 * Centralized Phase Configuration for the Fit Check Pipeline.
 * Maps backend phase names to UI display properties and styling.
 */
export const PHASE_CONFIG = {
  connecting: {
    label: 'Connecting',
    icon: Wifi,
    description: 'Classifying query and extracting entities',
    color: 'blue',
    borderColor: 'border-l-blue-400',
    bgColor: 'bg-blue-400',
    bgColorMuted: 'bg-blue-400/10',
    textColor: 'text-blue-400',
    ringColor: 'ring-blue-400/30',
    gradient: 'from-blue-400 to-blue-500',
    previewBorder: 'border-blue-400/50',
  },
  deep_research: {
    label: 'Deep Research',
    icon: Search,
    description: 'Gathering employer intelligence via web search',
    color: 'purple',
    borderColor: 'border-l-purple-400',
    bgColor: 'bg-purple-400',
    bgColorMuted: 'bg-purple-400/10',
    textColor: 'text-purple-400',
    ringColor: 'ring-purple-400/30',
    gradient: 'from-purple-400 to-purple-500',
    previewBorder: 'border-purple-400/50',
  },
  research_reranker: {
    label: 'Research Quality Gate',
    icon: CheckCircle2,
    description: 'Validating research completeness and quality',
    color: 'violet',
    borderColor: 'border-l-violet-400',
    bgColor: 'bg-violet-400',
    bgColorMuted: 'bg-violet-400/10',
    textColor: 'text-violet-400',
    ringColor: 'ring-violet-400/30',
    gradient: 'from-violet-400 to-violet-500',
    previewBorder: 'border-violet-400/50',
  },
  content_enrich: {
    label: 'Content Enrichment',
    icon: Database,
    description: 'Extracting full page content from top sources',
    color: 'cyan',
    borderColor: 'border-l-cyan-400',
    bgColor: 'bg-cyan-400',
    bgColorMuted: 'bg-cyan-400/10',
    textColor: 'text-cyan-400',
    ringColor: 'ring-cyan-400/30',
    gradient: 'from-cyan-400 to-cyan-500',
    previewBorder: 'border-cyan-400/50',
  },
  skeptical_comparison: {
    label: 'Skeptical Comparison',
    icon: Scale,
    description: 'Critical gap analysis between candidate and requirements',
    color: 'amber',
    borderColor: 'border-l-amber-400',
    bgColor: 'bg-amber-400',
    bgColorMuted: 'bg-amber-400/10',
    textColor: 'text-amber-400',
    ringColor: 'ring-amber-400/30',
    gradient: 'from-amber-400 to-amber-500',
    previewBorder: 'border-amber-400/50',
  },
  skills_matching: {
    label: 'Skills Matching',
    icon: Briefcase,
    description: 'Mapping skills to job requirements',
    color: 'emerald',
    borderColor: 'border-l-emerald-400',
    bgColor: 'bg-emerald-400',
    bgColorMuted: 'bg-emerald-400/10',
    textColor: 'text-emerald-400',
    ringColor: 'ring-emerald-400/30',
    gradient: 'from-emerald-400 to-emerald-500',
    previewBorder: 'border-emerald-400/50',
  },
  confidence_reranker: {
    label: 'Confidence Calibration',
    icon: CheckCircle2,
    description: 'LLM-as-Judge quality assessment and calibration',
    color: 'emerald',
    borderColor: 'border-l-emerald-400',
    bgColor: 'bg-emerald-400',
    bgColorMuted: 'bg-emerald-400/10',
    textColor: 'text-emerald-400',
    ringColor: 'ring-emerald-400/30',
    gradient: 'from-emerald-400 to-emerald-500',
    previewBorder: 'border-emerald-400/50',
  },
  generate_results: {
    label: 'Generating Results',
    icon: FileCheck2,
    description: 'Synthesizing final response with insights',
    color: 'burnt-peach',
    borderColor: 'border-l-burnt-peach',
    bgColor: 'bg-burnt-peach',
    bgColorMuted: 'bg-burnt-peach/10',
    textColor: 'text-burnt-peach',
    ringColor: 'ring-burnt-peach/30',
    gradient: 'from-burnt-peach to-burnt-peach/80',
    previewBorder: 'border-burnt-peach/50',
  },
};

/** Ordered list of pipeline phases */
export const PHASE_ORDER = [
  'connecting',
  'deep_research',
  'research_reranker',
  'content_enrich',
  'skeptical_comparison',
  'skills_matching',
  'confidence_reranker',
  'generate_results',
];
