/**
 * Pipeline Phase Configuration - AUTO-GENERATED
 * 
 * This module is AUTO-GENERATED from the profile/ directory (Single Point of Truth).
 * DO NOT EDIT THIS FILE DIRECTLY. Edit profile/pipeline_phases.json instead.
 * 
 * Source: scripts/generate-profile-config.js
 * Generated from: profile/pipeline_phases.json
 * 
 * IMPORTANT: All class names must be complete static strings for Tailwind to compile them.
 * Dynamic template literals will NOT work with Tailwind's static analysis.
 */

import { Briefcase, Database, FileCheck2, Scale, Search, ShieldCheck, Wifi, Zap } from 'lucide-react';

/**
 * Centralized Phase Configuration for the Fit Check Pipeline.
 * Maps backend phase names to UI display properties and styling.
 */
export const PHASE_CONFIG = {
  connecting: {
    label: 'Connecting',
    icon: Wifi,
    description: 'Classifying query and extracting entities',
    color: 'blue',
    borderColor: 'border-l-blue-400',
    bgColor: 'bg-blue-400',
    bgColorMuted: 'bg-blue-400/10',
    textColor: 'text-blue-400',
    ringColor: 'ring-blue-400/30',
    gradient: 'from-blue-400 to-blue-500',
    gradientFrom: 'from-blue-400/10',
    gradientFromLight: 'from-blue-500/5',
    previewBorder: 'border-blue-400/50',
    glowRGB: '96, 165, 250',
  },
  deep_research: {
    label: 'Deep Research',
    icon: Search,
    description: 'Gathering employer intelligence via web search',
    color: 'purple',
    borderColor: 'border-l-purple-400',
    bgColor: 'bg-purple-400',
    bgColorMuted: 'bg-purple-400/10',
    textColor: 'text-purple-400',
    ringColor: 'ring-purple-400/30',
    gradient: 'from-purple-400 to-purple-500',
    gradientFrom: 'from-purple-400/10',
    gradientFromLight: 'from-purple-500/5',
    previewBorder: 'border-purple-400/50',
    glowRGB: '192, 132, 252',
  },
  research_reranker: {
    label: 'Research Quality Gate',
    icon: ShieldCheck,
    description: 'Validating research completeness and quality',
    color: 'violet',
    borderColor: 'border-l-violet-400',
    bgColor: 'bg-violet-400',
    bgColorMuted: 'bg-violet-400/10',
    textColor: 'text-violet-400',
    ringColor: 'ring-violet-400/30',
    gradient: 'from-violet-400 to-violet-500',
    gradientFrom: 'from-violet-400/10',
    gradientFromLight: 'from-violet-500/5',
    previewBorder: 'border-violet-400/50',
    glowRGB: '167, 139, 250',
  },
  content_enrich: {
    label: 'Content Enrichment',
    icon: Database,
    description: 'Extracting full page content from top sources',
    color: 'cyan',
    borderColor: 'border-l-cyan-400',
    bgColor: 'bg-cyan-400',
    bgColorMuted: 'bg-cyan-400/10',
    textColor: 'text-cyan-400',
    ringColor: 'ring-cyan-400/30',
    gradient: 'from-cyan-400 to-cyan-500',
    gradientFrom: 'from-cyan-400/10',
    gradientFromLight: 'from-cyan-500/5',
    previewBorder: 'border-cyan-400/50',
    glowRGB: '34, 211, 238',
  },
  skeptical_comparison: {
    label: 'Skeptical Comparison',
    icon: Scale,
    description: 'Critical gap analysis between candidate and requirements',
    color: 'amber',
    borderColor: 'border-l-amber-400',
    bgColor: 'bg-amber-400',
    bgColorMuted: 'bg-amber-400/10',
    textColor: 'text-amber-400',
    ringColor: 'ring-amber-400/30',
    gradient: 'from-amber-400 to-amber-500',
    gradientFrom: 'from-amber-400/10',
    gradientFromLight: 'from-amber-500/5',
    previewBorder: 'border-amber-400/50',
    glowRGB: '251, 191, 36',
  },
  skills_matching: {
    label: 'Skills Matching',
    icon: Briefcase,
    description: 'Mapping skills to job requirements',
    color: 'emerald',
    borderColor: 'border-l-emerald-400',
    bgColor: 'bg-emerald-400',
    bgColorMuted: 'bg-emerald-400/10',
    textColor: 'text-emerald-400',
    ringColor: 'ring-emerald-400/30',
    gradient: 'from-emerald-400 to-emerald-500',
    gradientFrom: 'from-emerald-400/10',
    gradientFromLight: 'from-emerald-500/5',
    previewBorder: 'border-emerald-400/50',
    glowRGB: '52, 211, 153',
  },
  confidence_reranker: {
    label: 'Confidence Calibration',
    icon: Zap,
    description: 'LLM-as-Judge quality assessment and calibration',
    color: 'emerald',
    borderColor: 'border-l-emerald-400',
    bgColor: 'bg-emerald-400',
    bgColorMuted: 'bg-emerald-400/10',
    textColor: 'text-emerald-400',
    ringColor: 'ring-emerald-400/30',
    gradient: 'from-emerald-400 to-emerald-500',
    gradientFrom: 'from-emerald-400/10',
    gradientFromLight: 'from-emerald-500/5',
    previewBorder: 'border-emerald-400/50',
    glowRGB: '52, 211, 153',
  },
  generate_results: {
    label: 'Generating Results',
    icon: FileCheck2,
    description: 'Synthesizing final response with insights',
    color: 'burnt-peach',
    borderColor: 'border-l-burnt-peach',
    bgColor: 'bg-burnt-peach',
    bgColorMuted: 'bg-burnt-peach/10',
    textColor: 'text-burnt-peach',
    ringColor: 'ring-burnt-peach/30',
    gradient: 'from-burnt-peach to-burnt-peach',
    gradientFrom: 'from-burnt-peach/10',
    gradientFromLight: 'from-burnt-peach/5',
    previewBorder: 'border-burnt-peach/50',
    glowRGB: '224, 122, 95',
  }
};

/** Ordered list of pipeline phases */
export const PHASE_ORDER = [
  'connecting',
  'deep_research',
  'research_reranker',
  'content_enrich',
  'skeptical_comparison',
  'skills_matching',
  'confidence_reranker',
  'generate_results'
];
