/**
 * Profile Data - AUTO-GENERATED
 * 
 * This module is AUTO-GENERATED from the profile/ directory (Single Point of Truth).
 * DO NOT EDIT THIS FILE DIRECTLY. Edit the JSON files in profile/ instead.
 * 
 * Source: scripts/generate-profile-config.js
 * Generated from: profile/*.json
 */

// =============================================================================
// Identity & Bio
// =============================================================================

export const IDENTITY = {
  $schema: './schemas/identity.schema.json',
  name: {
    full: 'Jaden Bruha',
    display: 'Jaden Bruha',
    title: 'Technical Engineer',
    professional_title: 'Software Engineer'
  },
  portrait: {
    path: '/resources/portrait.jpg',
    alt: 'Jaden Bruha Portrait'
  },
  hero: {
    animation_left: 'I\'m Jaden Bruha',
    animation_right: 'A Technical Engineer'
  },
  bio: {
    tldr: 'TLDR; I am Jaden Bruha, I\'m a 22 year old new-grad, and I\'m a very nerdy engineer with big aspirations.',
    full: 'I have a passion for building anything and everything from software, computers to serve my software, AI agents, and motorcycles. My journey started at a young age as a hobbyist, and I\'ve grown into a full stack developer striving for elegant solutions. My current fixations include learning about quantum philosophy, parallelized programming, and artificial (general) intelligence.'
  },
  experience_summary: 'Full-stack software engineer with experience building modern web applications and AI-powered systems. Proficient in developing scalable backend services, responsive frontend interfaces, and integrating cutting-edge AI/ML capabilities.\n\nKey accomplishments:\n- Built production AI agents using LangChain and LangGraph\n- Developed full-stack applications with React/Next.js and FastAPI\n- Implemented real-time streaming features using SSE and WebSockets\n- Designed and deployed containerized microservices architecture\n- Created RAG systems for intelligent document processing',
  strengths: ['Fast learner who quickly adapts to new technologies', 'Strong problem-solving and debugging skills', 'Experience with end-to-end software development lifecycle', 'Excellent communication and collaboration abilities', 'Passionate about building AI-powered applications'],
  career_interests: ['Full-Stack Development', 'AI/ML Engineering', 'Backend Systems', 'Cloud Architecture', 'Developer Tools']
};

// =============================================================================
// Skills & Technologies
// =============================================================================

export const SKILLS = {
  $schema: './schemas/skills.schema.json',
  display_categories: {
    primary: {
      label: 'Skills & Technologies',
      skills: ['TODO']
    },
    devops: {
      label: 'Dev Ops',
      skills: ['Jira', 'Slack', 'Git', 'Github', 'Figma', 'Excel Sheets', 'CapCut']
    }
  },
  backend_categories: {
    languages: ['Python', 'JavaScript', 'TypeScript', 'SQL', 'HTML/CSS'],
    frameworks: ['React', 'Next.js', 'FastAPI', 'Node.js', 'TailwindCSS'],
    cloud_devops: ['Docker', 'AWS', 'PostgreSQL', 'Redis', 'CI/CD'],
    ai_ml: ['LangChain', 'LangGraph', 'OpenAI API', 'Google Gemini', 'RAG Systems', 'Prompt Engineering'],
    tools: ['Git', 'VS Code', 'Linux', 'REST APIs', 'GraphQL']
  }
};

// =============================================================================
// Projects
// =============================================================================

export const PROJECTS = {
  $schema: './schemas/projects.schema.json',
  featured: [
    {
      id: 'project-alpha',
      title: 'Project Alpha',
      description: 'A full-stack web application built with React and Node.js, featuring real-time updates and modern UI.',
      about: 'Project Alpha is a comprehensive full-stack application that demonstrates modern web development practices. It features a React frontend with a Node.js backend, utilizing WebSocket connections for real-time updates. The application includes user authentication, data persistence with PostgreSQL, and a responsive design that works seamlessly across all devices.',
      learning_outcomes: ['Mastered React hooks and state management patterns', 'Implemented WebSocket connections for real-time data synchronization', 'Designed and optimized PostgreSQL database schemas', 'Built RESTful APIs with proper error handling and validation', 'Deployed containerized applications using Docker'],
      tags: ['React', 'Node.js', 'PostgreSQL'],
      color: 'from-burnt-peach to-apricot',
      images_folder: 'project-alpha',
      link: null
    },
    {
      id: 'project-beta',
      title: 'Project Beta',
      description: 'Mobile-first progressive web app with offline capabilities and push notifications.',
      about: 'Project Beta showcases the power of Progressive Web Apps (PWAs) with a mobile-first approach. The application leverages service workers for offline functionality, implements push notifications for user engagement, and provides a native app-like experience directly in the browser. Built with Next.js and TypeScript for type safety and improved developer experience.',
      learning_outcomes: ['Implemented service workers for offline-first functionality', 'Configured push notifications with proper permission handling', 'Utilized TypeScript for enhanced code quality and maintainability', 'Optimized performance with Next.js static generation and caching', 'Designed responsive layouts following mobile-first principles'],
      tags: ['Next.js', 'PWA', 'TypeScript'],
      color: 'from-muted-teal to-twilight',
      images_folder: 'project-beta',
      link: null
    },
    {
      id: 'project-gamma',
      title: 'Project Gamma',
      description: 'Data visualization dashboard with interactive charts and real-time analytics.',
      about: 'Project Gamma is an advanced data visualization dashboard that transforms complex datasets into intuitive, interactive visualizations. Using D3.js for custom charts and Python for backend data processing, the dashboard provides real-time analytics with filtering, zooming, and drill-down capabilities. The system processes large datasets efficiently and presents insights in a visually compelling manner.',
      learning_outcomes: ['Created custom D3.js visualizations with interactive features', 'Built efficient data processing pipelines in Python', 'Implemented real-time data streaming and updates', 'Designed intuitive UX for complex data exploration', 'Optimized rendering performance for large datasets'],
      tags: ['Python', 'D3.js', 'PostgreSQL'],
      color: 'from-apricot to-muted-teal',
      images_folder: 'project-gamma',
      link: null
    }
  ],
  backend_projects: [
    {
      name: 'AI Portfolio Assistant',
      description: 'Real-time AI agent that analyzes employer fit using web research and skill matching',
      tech: ['Python', 'FastAPI', 'LangGraph', 'React', 'SSE Streaming']
    },
    {
      name: 'Full-Stack Web Platform',
      description: 'Production web application with authentication, real-time features, and cloud deployment',
      tech: ['Next.js', 'FastAPI', 'PostgreSQL', 'Docker', 'AWS']
    },
    {
      name: 'RAG Document System',
      description: 'Intelligent document retrieval and question-answering system',
      tech: ['LangChain', 'Vector Databases', 'OpenAI', 'Python']
    }
  ]
};

// =============================================================================
// Education
// =============================================================================

export const EDUCATION = {
  $schema: './schemas/education.schema.json',
  primary: {
    degree: 'Bachelor of Science Degree in Computer Science',
    institution: 'California State University, Sacramento',
    graduation: '2025 Winter Graduate',
    logo_path: '/resources/school_logo.png'
  },
  certifications: []
};

// =============================================================================
// Contact Information
// =============================================================================

export const CONTACT = {
  $schema: './schemas/contact.schema.json',
  email: 'hello@example.com',
  social: {
    github: {
      url: 'https://github.com/bassnp',
      display: 'bassnp'
    },
    mail: {
      url: 'mailto:hello@example.com',
      display: 'Email'
    }
  },
  repo: {
    url: 'https://github.com/bassnp/res_web',
    display: 'View Source Code'
  }
};

// =============================================================================
// Assets
// =============================================================================

export const ASSETS = {
  $schema: './schemas/assets.schema.json',
  portrait: '/resources/portrait.jpg',
  school_logo: '/resources/school_logo.png',
  resume_pdf: {
    path: '/resources/SSR_TSRPT.pdf',
    thumbnail: '/resources/SSR_TSRPT_thumb.jpg',
    label: 'PDF Formatted Resume'
  },
  personal_collage: {
    folder: '/resources/personal_collage/',
    manifest: '/resources/collage_manifest.json'
  },
  project_images_base: '/resources/project_images/',
  timeline_images_base: '/resources/timeline_images/'
};

// =============================================================================
// Site Metadata
// =============================================================================

export const SITE_METADATA = {
  $schema: './schemas/site_metadata.schema.json',
  site: {
    title: 'Portfolio | Software Engineer',
    description: 'Personal resume and portfolio showcasing projects and work experience',
    og_image: '/resources/og-image.png'
  },
  theme: {
    default: 'system'
  },
  deployment: {
    backend_port: 8000,
    frontend_port: 3003,
    api_base_url_dev: 'http://localhost:8000',
    frontend_url_dev: 'http://localhost:3003',
    cors_origins: ['http://localhost:3003']
  },
  repository: {
    name: 'res_web',
    image_name: 'res_web',
    image_tag: 'latest',
    maintainer: 'res_web',
    source: 'https://github.com/bassnp/res_web'
  }
};

// =============================================================================
// Experience Timeline
// =============================================================================

export const EXPERIENCE = {
  $schema: './schemas/experience.schema.json',
  timeline: [
    {
      id: 1,
      title: 'Software Engineer',
      company: 'Tech Innovation Corp',
      period: 'December 2025',
      description: 'Leading full-stack development initiatives, architecting scalable solutions with React, Node.js, and cloud services. Implementing CI/CD pipelines and mentoring junior developers.',
      tags: ['React', 'Node.js', 'AWS', 'TypeScript'],
      color: 'burnt-peach',
      showcase_folder: 'showcase1'
    },
    {
      id: 2,
      title: 'Full Stack Developer',
      company: 'Digital Solutions Inc',
      period: '2024',
      description: 'Built and deployed production-ready web applications serving thousands of users. Optimized database queries resulting in 40% performance improvement.',
      tags: ['Next.js', 'PostgreSQL', 'Docker'],
      color: 'muted-teal',
      showcase_folder: 'showcase2'
    },
    {
      id: 3,
      title: 'Software Development Intern',
      company: 'StartupXYZ',
      period: '2023',
      description: 'Developed RESTful APIs and integrated third-party services. Contributed to agile sprints and participated in code reviews with senior engineers.',
      tags: ['Python', 'FastAPI', 'Git'],
      color: 'apricot',
      showcase_folder: 'showcase3'
    },
    {
      id: 4,
      title: 'Freelance Web Developer',
      company: 'Self-Employed',
      period: '2022',
      description: 'Delivered custom websites and e-commerce solutions for small businesses. Managed client relationships and project timelines independently.',
      tags: ['JavaScript', 'WordPress', 'CSS'],
      color: 'burnt-peach',
      showcase_folder: 'showcase4'
    },
    {
      id: 5,
      title: 'Research Assistant',
      company: 'University CS Department',
      period: '2020',
      description: 'Assisted in machine learning research projects. Processed datasets, implemented algorithms, and co-authored a conference paper on NLP techniques.',
      tags: ['Python', 'TensorFlow', 'NLP'],
      color: 'muted-teal',
      showcase_folder: 'showcase5'
    },
    {
      id: 6,
      title: 'IT Support Technician',
      company: 'Campus Tech Services',
      period: '2018',
      description: 'Provided technical support for faculty and students. Troubleshot hardware/software issues and maintained computer lab equipment.',
      tags: ['Troubleshooting', 'Windows', 'Linux'],
      color: 'apricot',
      showcase_folder: 'showcase6'
    },
    {
      id: 7,
      title: 'Programming Hobbyist',
      company: 'Self-Taught Journey',
      period: '2016',
      description: 'Discovered passion for programming through game development and automation scripts. Built first website and learned fundamentals of coding logic.',
      tags: ['Java', 'HTML', 'CSS'],
      color: 'burnt-peach',
      showcase_folder: 'showcase7'
    }
  ]
};

// =============================================================================
// Convenience Exports
// =============================================================================

// API Configuration
export const API_BASE_URL = SITE_METADATA.deployment.api_base_url_dev;

// Hero Section
export const HERO_TEXT = {
  left: IDENTITY.hero.animation_left,
  right: IDENTITY.hero.animation_right,
};

// Skills for display
export const PRIMARY_SKILLS = SKILLS.display_categories.primary.skills;
export const DEVOPS_SKILLS = SKILLS.display_categories.devops.skills;

// Projects for display
export const FEATURED_PROJECTS = PROJECTS.featured;

// Education for display
export const PRIMARY_EDUCATION = EDUCATION.primary;

// Contact for display
export const EMAIL = CONTACT.email;
export const GITHUB_URL = CONTACT.social.github.url;
export const GITHUB_USERNAME = CONTACT.social.github.display;
export const REPO_URL = CONTACT.repo.url;

// Portrait
export const PORTRAIT_PATH = ASSETS.portrait;
export const PORTRAIT_ALT = IDENTITY.portrait.alt;

// Bio
export const BIO_TLDR = IDENTITY.bio.tldr;
export const BIO_FULL = IDENTITY.bio.full;
