/**
 * Profile Data - AUTO-GENERATED
 * 
 * This module is AUTO-GENERATED from the profile/ directory (Single Point of Truth).
 * DO NOT EDIT THIS FILE DIRECTLY. Edit the JSON files in profile/ instead.
 * 
 * Source: scripts/generate-profile-config.js
 * Generated from: profile/*.json
 */

// =============================================================================
// Identity & Bio
// =============================================================================

export const IDENTITY = {
  $schema: './schemas/identity.schema.json',
  name: {
    full: 'Jaden Bruha',
    display: 'Jaden Bruha',
    title: 'Technical Engineer',
    professional_title: 'Software Engineer'
  },
  portrait: {
    path: '/resources/portrait.jpg',
    alt: 'Jaden Bruha Portrait'
  },
  hero: {
    animation_left: 'I\'m Jaden Bruha',
    animation_right: 'A Technical Engineer'
  },
  bio: {
    tldr: 'TLDR; I am Jaden Bruha, I\'m a 22 year old new-grad, and I\'m a very nerdy engineer with big aspirations.',
    full: 'I have a passion for building anything and everything from software, computers to serve my software, AI agents, and motorcycles. My journey started at a young age as a hobbyist, and I\'ve grown into a full stack developer striving for elegant solutions. My current fixations include learning about quantum philosophy, parallelized programming, and artificial (general) intelligence.'
  },
  experience_summary: 'Full-stack software engineer and December 2025 CSU Sacramento graduate specializing in AI-powered applications and agentic systems. Experienced in building production platforms from concept to client delivery.\n\nKey accomplishments:\n- Delivered ChurchLink platform to production—a Web & App Builder with localization and payment processing for a real church client\n- Built a Deep Researcher Agent using LangGraph and Google CSE for graph-based web research orchestration\n- Created Zharvis, an Overwolf gaming overlay SaaS with RAG pipelines processing 15k+ wiki documents\n- First profitable SaaS at age 19, generating $6k revenue with a team of 3 developers\n- Self-taught foundation starting with first GitHub commit at age 15',
  strengths: ['Rapid learner who quickly adapts to new technologies and frameworks', 'Hands-on experience shipping production software to real clients', 'Deep expertise in AI/ML tooling including LangChain, LangGraph, and RAG systems', 'Full-stack capabilities spanning Flutter, React, FastAPI, and cloud infrastructure', 'Entrepreneurial mindset with proven ability to generate revenue from software products'],
  career_interests: ['AI/ML Engineering & Agentic Systems', 'Full-Stack Development', 'Backend Systems & APIs', 'Developer Tools & Productivity', 'Gaming & Interactive Applications']
};

// =============================================================================
// Skills & Technologies
// =============================================================================

export const SKILLS = {
  $schema: './schemas/skills.schema.json',
  display_categories: {
    primary: {
      label: 'Skills & Technologies',
      skills: ['Python', 'JavaScript', 'TypeScript', 'Dart', 'Flutter', 'FastAPI', 'LangGraph', 'LangChain', 'React', 'Next.js', 'Lua', 'Java']
    },
    devops: {
      label: 'DevOps & Tools',
      skills: ['Docker', 'Firebase', 'MongoDB', 'Git', 'GitHub', 'Jira', 'Slack', 'Figma', 'CapCut']
    }
  },
  backend_categories: {
    languages: ['Python', 'JavaScript', 'TypeScript', 'Dart', 'Lua', 'Java', 'SQL', 'HTML/CSS'],
    frameworks: ['Flutter', 'React', 'Next.js', 'Vite', 'FastAPI', 'Node.js', 'TailwindCSS', 'Radix UI', 'Shadcn UI'],
    cloud_devops: ['Docker', 'Firebase', 'MongoDB', 'PostgreSQL', 'Redis', 'PayPal Integration', 'CI/CD'],
    ai_ml: ['LangChain', 'LangGraph', 'LangSmith', 'OpenAI API', 'Google Gemini', 'RAG Systems', 'MCP Servers', 'Prompt Engineering', 'Vector Stores'],
    tools: ['Git', 'GitHub', 'VS Code', 'Overwolf SDK', 'Linux', 'REST APIs']
  }
};

// =============================================================================
// Projects
// =============================================================================

export const PROJECTS = {
  $schema: './schemas/projects.schema.json',
  featured: [
    {
      id: 'churchlink',
      title: 'ChurchLink - Web & App Builder Platform',
      description: 'As part of my Senior Graduation Project, I teamed up with 6 other computer science engineers to develop and deploy a platform to build website and mobile pages to dynamiclly customize features for a client.',
      about: 'ChurchLink is a comprehensive church management platofrm developed for senior project graduation requirement with a team of 6 other students to from a strong bond as a team to offer a robust and user-friendly software deliverable. The platform provides an intuitive web and app features for churches to create and customize their digital presence across multiple platforms. Key features include localization for multi-language congregations, administrative dashboards for content management, and integrated PayPal payment processing for donations and events. The solution was successfully handed off to our client at Second Slavic Baptist Church as of December 2025.',
      learning_outcomes: ['Collaborated in a 6-person agile team through full development lifecycle utilzing Jira and GitHub Projects for sprint management and version control', 'Each team member\'s role was to have no role - everyone contributed to all aspects of the project to learn every aspect of the modern software development lifecycle', 'Architected backend services using FastAPI with Firebase and MongoDB integration to sync across web and mobile clients', 'Implemented client desireables offering multi-language localizations per-feature for diverse congregations'],
      tags: ['Python', 'Flutter', 'TypeScript', 'Vite', 'FastAPI', 'Firebase', 'MongoDB', 'PayPal'],
      color: 'from-burnt-peach to-apricot',
      images_folder: 'project-churchlink',
      link: null
    },
    {
      id: 'cse-agent',
      title: 'Google Gemini GenUI & CSE Deep Researcher Agent',
      description: 'To learn the fundemtnals of building modern AI Agents, I built this agentic research system using LangGraph and Google Custom Search Engine to generate structured UI reports with images, tables, and sourced web content.',
      about: 'In this project I set out to create a sophisticated web research agent powered by LangGraph\'s graph-theory based orchestration to leverage Google\'s Custom Search Engine (CSE) to perform deep web analysis and research, systematically compiling accurate context into structured Generative UI reports. The architecture demonstrates my passion for building agents and workflows with Retreival Augmented Generation (RAG) for accurate and nuanced web searching capabilities.',
      learning_outcomes: ['Designed graph-based agent orchestration using LangGraph for web analysis', 'Integrated Google CSE API for web research and context retrieval', 'Learned cutting edge Generative UI mechanisms for dynamic and visually appealing report generation', 'Deployed containerized services with Docker, Redis for caching, and Firebase for user auth'],
      tags: ['Google Gemini', 'LangGraph', 'Python', 'FastAPI', 'Firebase', 'Redis', 'Docker'],
      color: 'from-muted-teal to-twilight',
      images_folder: 'project-cse-agent',
      link: null
    },
    {
      id: 'zharvis',
      title: 'Zharvis - Videogame AI Overlay Agent',
      description: '(WIP) A SaaS Overwolf overlay providing real-time in-game AI assistance through Wiki-powered deep research and interactive HUD using Windows-like popups and components.',
      about: 'Zharvis is a next-gen gaming companion built on the Overwolf SDK to serve an overlay for any videogame. The current Version 2 utilizes dockerized pods for horizontal scaling to provide a LangChain pipeline with Custom Search Engines for videogame Wikis and Model Context Protocol (MCP) tools to have Gemini AI models build a Generative UI HUD with interactive windows and popups. The first iteration pioneered an archaic demo RAG workflow processing 15,000+ scraped wiki documents through vector stores with embedding and indexing for fast and efficient retrieval - however at the downside of accuracy. Now, the system enables gamers to access game knowledge without leaving their session or tab out of their game.',
      learning_outcomes: ['Overwolf SDK overlay application with TypeScript integration', 'MCP server architecture for extensible tool capabilities', 'Built multiple RAG pipeline interations to accurately process large domains of data', 'Created real-time Generative UI components for in-game HUD display', 'Integrated Gemini and LangChain for natural language query processing'],
      tags: ['Gemini', 'Overwolf', 'TypeScript', 'Python', 'FastAPI', 'Docker', 'LangChain'],
      color: 'from-apricot to-muted-teal',
      images_folder: 'project-zharvis',
      link: null
    }
  ],
  backend_projects: [
    {
      name: 'Google Gemini GenUI & CSE Deep Researcher Agent',
      description: 'Agentic research system using LangGraph and Google Custom Search Engine to generate structured UI reports',
      tech: ['Google Gemini', 'LangGraph', 'Python', 'FastAPI', 'Firebase', 'Redis', 'Docker']
    },
    {
      name: 'ChurchLink - Web & App Builder Platform',
      description: 'Full-stack church management system with cross-platform apps, multilingual localization, and payment integration',
      tech: ['Python', 'FastAPI', 'Firebase', 'MongoDB', 'Flutter', 'TypeScript', 'PayPal']
    },
    {
      name: 'Zharvis - Videogame AI Overlay Agent',
      description: 'SaaS Overwolf overlay providing real-time in-game AI assistance through Wiki-powered deep research and interactive HUD',
      tech: ['Gemini', 'Python', 'FastAPI', 'LangChain', 'MCP', 'Docker', 'Overwolf SDK']
    }
  ]
};

// =============================================================================
// Education
// =============================================================================

export const EDUCATION = {
  $schema: './schemas/education.schema.json',
  primary: {
    degree: 'Bachelor of Science Degree in Computer Science',
    institution: 'California State University, Sacramento',
    graduation: '2025 Winter Graduate',
    logo_path: '/resources/school_logo.png'
  },
  certifications: []
};

// =============================================================================
// Contact Information
// =============================================================================

export const CONTACT = {
  $schema: './schemas/contact.schema.json',
  email: 'jbruha@csus.edu',
  social: {
    github: {
      url: 'https://github.com/bassnp',
      display: 'bassnp'
    },
    mail: {
      url: 'mailto:jbruha@csus.edu',
      display: 'Email'
    }
  },
  repo: {
    url: 'https://github.com/bassnp/res_web',
    display: 'View Source Code'
  }
};

// =============================================================================
// Assets
// =============================================================================

export const ASSETS = {
  $schema: './schemas/assets.schema.json',
  portrait: '/resources/portrait.jpg',
  school_logo: '/resources/school_logo.png',
  resume_pdf: {
    path: '/resources/SSR_TSRPT.pdf',
    thumbnail: '/resources/SSR_TSRPT_thumb.jpg',
    label: 'PDF Resume'
  },
  personal_collage: {
    folder: '/resources/personal_collage/',
    manifest: '/resources/collage_manifest.json'
  },
  project_images_base: '/resources/project_images/',
  timeline_images_base: '/resources/timeline_images/'
};

// =============================================================================
// Site Metadata
// =============================================================================

export const SITE_METADATA = {
  $schema: './schemas/site_metadata.schema.json',
  site: {
    title: 'Jaden Bruha | Software Engineer',
    description: 'Jaden Bruha\'s Interactive portfolio with AI powered integrations.',
    og_image: '/resources/og-image.png'
  },
  theme: {
    default: 'system'
  },
  deployment: {
    backend_port: 8000,
    frontend_port: 3003,
    api_base_url_dev: 'http://localhost:8000',
    frontend_url_dev: 'http://localhost:3003',
    cors_origins: ['http://localhost:3003']
  },
  repository: {
    name: 'res_web',
    image_name: 'res_web',
    image_tag: 'latest',
    maintainer: 'Jaden Bruha',
    source: 'https://github.com/bassnp/res_web'
  }
};

// =============================================================================
// Experience Timeline
// =============================================================================

export const EXPERIENCE = {
  $schema: './schemas/experience.schema.json',
  timeline: [
    {
      id: 1,
      title: 'Bachelor of Science, Computer Science',
      company: 'California State University Sacramento Graduate',
      period: 'December 2025',
      description: 'Completed a Bachelor of Science Degree in Computer Science at California State University, Sacramento. Starting during the Covid-19 pandemic years, I rigorously pursued my academic passion where I met many friends along the way to help me grow as both a student and individual in this field.',
      tags: ['B.S. Computer Science', 'Winter 2025 New Grad'],
      color: 'burnt-peach',
      showcase_folder: 'showcase-graduation'
    },
    {
      id: 2,
      title: 'Graduation Senior Project Handoff',
      company: 'Second Slavic Baptist Church of Sacramento',
      period: 'November 2025',
      description: 'After a year-long upper-division course, my project team \'Init to Winit\' successfully delivered a rich Web & App Builder Platform to our client. The system enables church staff to manage content for many features across multiple platforms, handle multi-language localization, and process donations.',
      tags: ['Flutter', 'TypeScript', 'Python', 'Firebase', 'MongoDB'],
      color: 'muted-teal',
      showcase_folder: 'showcase-graduation'
    },
    {
      id: 3,
      title: 'Deep Researcher Agent w/ Generative UI',
      company: 'Personal Project',
      period: 'November 2025',
      description: 'Built a GenUI Deep Researcher Agent integrating Google\'s Custom Search Engine API with a LangGraph agent framework. The system uses graph-theory orchestration to scrape the web and compile structured reports featuring images, tables, and source citations.',
      tags: ['LangGraph', 'Google CSE', 'GenUI'],
      color: 'apricot',
      showcase_folder: 'showcase-cse-agent'
    },
    {
      id: 4,
      title: 'Zharvis Game Overlay',
      company: 'SaaS WIP Product',
      period: 'October 2025',
      description: 'Zharvis is an on-going project on the Overwolf Marketplace to host my overlay providing AI-powered in-game assistance. Version 2 upgraded from a v1 vector store RAG knowledge base to a Wiki CSE w/ MCP tooling methodology for faster and accurate query responses enabling a scalable product.',
      tags: ['Python', 'Overwolf', 'MCP', 'LangChain'],
      color: 'burnt-peach',
      showcase_folder: 'showcase-zharvis'
    },
    {
      id: 5,
      title: 'First SaaS Success',
      company: 'CS:GO Modding Team & Freelancer',
      period: 'January 2023',
      description: 'With a team of 3 friends and developers, we primarily set out to build and sell videogame mods for CS:GO. Over the course of a year we generated $6k in revenue through community engagement for freelancing private and public modding projects (see some minor ones on my Github)',
      tags: ['SAAS', 'Team Project', 'Lua'],
      color: 'muted-teal',
      showcase_folder: 'showcase-csgo'
    },
    {
      id: 6,
      title: 'GPU Mining Rig',
      company: 'Personal Project',
      period: 'April 2022',
      description: 'To help fund my early college years, I assembled a 7-GPU Ethereum mining rig using affordable Nvidia and AMD cards, achieving ~210 MH/s. It generated ~$170 as monthly passive income before the Ethereum Merge ended Proof of Work mining.',
      tags: ['Ethereum', 'GPU Parrallelism', 'Rig Building'],
      color: 'apricot',
      showcase_folder: 'showcase-mining'
    },
    {
      id: 7,
      title: 'First Git Commit',
      company: 'High School Side Project',
      period: 'July 2019',
      description: 'July 1st I pushed my first commit to GitHub at age 15, showcasing a Java drawing application I made out of boredom during my sophomore programming Java split-honors class of beginners and advanced students (shout-out Mr.McGuinness ur awesome). This minor milestone marked the beginning of my ambitious journey as a software developer.',
      tags: ['Highschool', 'Honors Class', 'First Git Commit'],
      color: 'burnt-peach',
      showcase_folder: 'showcase-first-commit'
    }
  ]
};

// =============================================================================
// Convenience Exports
// =============================================================================

// API Configuration
export const API_BASE_URL = SITE_METADATA.deployment.api_base_url_dev;

// Hero Section
export const HERO_TEXT = {
  left: IDENTITY.hero.animation_left,
  right: IDENTITY.hero.animation_right,
};

// Skills for display
export const PRIMARY_SKILLS = SKILLS.display_categories.primary.skills;
export const DEVOPS_SKILLS = SKILLS.display_categories.devops.skills;

// Projects for display
export const FEATURED_PROJECTS = PROJECTS.featured;

// Education for display
export const PRIMARY_EDUCATION = EDUCATION.primary;

// Contact for display
export const EMAIL = CONTACT.email;
export const GITHUB_URL = CONTACT.social.github.url;
export const GITHUB_USERNAME = CONTACT.social.github.display;
export const REPO_URL = CONTACT.repo.url;

// Portrait
export const PORTRAIT_PATH = ASSETS.portrait;
export const PORTRAIT_ALT = IDENTITY.portrait.alt;

// Bio
export const BIO_TLDR = IDENTITY.bio.tldr;
export const BIO_FULL = IDENTITY.bio.full;
