/**
 * Profile Data - AUTO-GENERATED
 * 
 * This module is AUTO-GENERATED from the profile/ directory (Single Point of Truth).
 * DO NOT EDIT THIS FILE DIRECTLY. Edit the JSON files in profile/ instead.
 * 
 * Source: scripts/generate-profile-config.js
 * Generated from: profile/*.json
 */

// =============================================================================
// Identity & Bio
// =============================================================================

export const IDENTITY = {
  $schema: './schemas/identity.schema.json',
  name: {
    full: 'Jaden Bruha',
    display: 'Jaden Bruha',
    title: 'Technical Engineer',
    professional_title: 'Software Engineer'
  },
  portrait: {
    path: '/resources/portrait.jpg',
    alt: 'Jaden Bruha Portrait'
  },
  hero: {
    animation_left: 'I\'m Jaden Bruha',
    animation_right: 'A Technical Engineer'
  },
  bio: {
    tldr: 'TLDR; I am Jaden Bruha, I\'m a 22 year old new-grad, and I\'m a very nerdy engineer with big aspirations.',
    full: 'I have a passion for building anything and everything from software, computers to serve my software, AI agents, and motorcycles. My journey started at a young age as a hobbyist, and I\'ve grown into a full stack developer striving for elegant solutions. My current fixations include learning about quantum philosophy, parallelized programming, and artificial (general) intelligence.'
  },
  experience_summary: 'Full-stack software engineer with experience building modern web applications and AI-powered systems. Proficient in developing scalable backend services, responsive frontend interfaces, and integrating cutting-edge AI/ML capabilities.\n\nKey accomplishments:\n- Built production AI agents using LangChain and LangGraph\n- Developed full-stack applications with React/Next.js and FastAPI\n- Implemented real-time streaming features using SSE and WebSockets\n- Designed and deployed containerized microservices architecture\n- Created RAG systems for intelligent document processing',
  strengths: ['Fast learner who quickly adapts to new technologies', 'Strong problem-solving and debugging skills', 'Experience with end-to-end software development lifecycle', 'Excellent communication and collaboration abilities', 'Passionate about building AI-powered applications'],
  career_interests: ['Full-Stack Development', 'AI/ML Engineering', 'Backend Systems', 'Cloud Architecture', 'Developer Tools']
};

// =============================================================================
// Skills & Technologies
// =============================================================================

export const SKILLS = {
  $schema: './schemas/skills.schema.json',
  display_categories: {
    primary: {
      label: 'Skills & Technologies',
      skills: ['Python', 'Lua', 'Java', 'JavaScript', 'Dart', 'TypeScript', 'React', 'Next.js', 'FastAPI', 'LangChain', 'LangGraph', 'Flutter', 'Vite', 'Firebase', 'MongoDB', 'Docker', 'AWS', 'PostgreSQL', 'Redis']
    },
    devops: {
      label: 'Dev Ops',
      skills: ['Jira', 'Slack', 'Git', 'GitHub', 'Figma', 'Excel Sheets', 'CapCut']
    }
  },
  backend_categories: {
    languages: ['Python', 'JavaScript', 'TypeScript', 'SQL', 'HTML/CSS'],
    frameworks: ['React', 'Next.js', 'FastAPI', 'Node.js', 'TailwindCSS'],
    cloud_devops: ['Docker', 'AWS', 'PostgreSQL', 'Redis', 'CI/CD'],
    ai_ml: ['LangChain', 'LangGraph', 'OpenAI API', 'Google Gemini', 'RAG Systems', 'Prompt Engineering'],
    tools: ['Git', 'VS Code', 'Linux', 'REST APIs', 'GraphQL']
  }
};

// =============================================================================
// Projects
// =============================================================================

export const PROJECTS = {
  $schema: './schemas/projects.schema.json',
  featured: [
    {
      id: 'churchlink',
      title: 'ChurchLink — Team of 6, Graduation Project',
      description: 'Deployed Web Builder Platform for Churches to customize a Website + App w/ Localization, Admin Dashboards, & Payments',
      about: 'ChurchLink is a comprehensive platform that empowers churches to create and manage their online presence. The system provides a drag-and-drop web builder, cross-platform mobile app, localization support, admin dashboards for content management, and integrated payment processing. Built as a graduation project with a team of 6, this platform demonstrates full-stack development, team collaboration, and deployment expertise.',
      learning_outcomes: ['Mastered Flutter cross-platform development for iOS and Android', 'Implemented complex payment integrations with PayPal', 'Designed scalable NoSQL database architecture with MongoDB', 'Coordinated team of 6 using Agile methodologies'],
      tags: ['Python', 'Flutter', 'TypeScript', 'Vite', 'FastAPI', 'Firebase', 'MongoDB', 'PayPal'],
      color: 'from-burnt-peach to-apricot',
      images_folder: 'project-churchlink',
      link: null
    },
    {
      id: 'google-cse-agent',
      title: 'Google CSE Agent — GenUI Web Researcher',
      description: 'Agentic LangGraph Deep Researcher w/ CSE Web-Research + RAG GenUI Pipeline',
      about: 'An intelligent research agent powered by Google Custom Search Engine and LangGraph orchestration. The system performs deep web research, extracts relevant information, and generates contextual UI components on-the-fly. Features include agentic reasoning, RAG (Retrieval-Augmented Generation) pipeline, and real-time UI generation based on research findings.',
      learning_outcomes: ['Built production-grade LangGraph agentic workflows', 'Implemented RAG systems with vector databases', 'Integrated Google Custom Search Engine API', 'Deployed containerized microservices with Docker'],
      tags: ['Google Gemini', 'LangGraph', 'LangSmith', 'Python', 'FastAPI', 'Firebase', 'Redis', 'Docker'],
      color: 'from-muted-teal to-twilight',
      images_folder: 'project-cse-agent',
      link: null
    },
    {
      id: 'interactive-portfolio',
      title: 'My Interactive Portfolio — Made for Employers!',
      description: 'Assess my resume w/ a comparative Deep Researcher that brutally analyzes my resume against job descriptions/positions',
      about: 'A cutting-edge portfolio website that features an AI-powered Fit Check system. Employers can input a job description or company name, and the system performs deep web research to compare requirements against my skills and experience. The multi-phase pipeline provides transparent reasoning, skill matching, and an honest assessment of fit - demonstrating both technical capability and professional transparency.',
      learning_outcomes: ['Architected multi-phase LangGraph pipeline with conditional routing', 'Implemented Server-Sent Events (SSE) for real-time streaming', 'Designed component-based UI architecture with Radix UI', 'Deployed full-stack application with Docker orchestration'],
      tags: ['Radix UI', 'Shadcn/ui', 'Next.js', 'Python', 'FastAPI', 'Docker', 'LangGraph'],
      color: 'from-twilight to-muted-teal',
      images_folder: 'project-portfolio',
      link: 'https://github.com/bassnp/res_web'
    },
    {
      id: 'videogame-agent',
      title: 'Videogame Agent & MCP — Overwolf Overlay',
      description: 'RAG workflow + MCP server + In-Game-Overlay = Generative UI HUD w/ Windows & Popups for real-time assistance',
      about: 'An innovative in-game AI assistant that provides real-time help through an Overwolf overlay. The system combines RAG (Retrieval-Augmented Generation) workflows with Model Context Protocol (MCP) server architecture to deliver contextual assistance directly within the game. Features generative UI with dynamic windows and popups that adapt to gameplay context.',
      learning_outcomes: ['Integrated Overwolf API for in-game overlay development', 'Implemented Model Context Protocol (MCP) server', 'Built RAG workflow for game-specific knowledge retrieval', 'Optimized performance for real-time in-game operation'],
      tags: ['OpenAI', 'Overwolf', 'TypeScript', 'Python', 'FastAPI', 'Docker', 'LangChain'],
      color: 'from-apricot to-burnt-peach',
      images_folder: 'project-videogame-agent',
      link: null
    }
  ],
  backend_projects: [
    {
      name: 'AI Portfolio Assistant',
      description: 'Real-time AI agent that analyzes employer fit using web research and skill matching',
      tech: ['Python', 'FastAPI', 'LangGraph', 'React', 'SSE Streaming']
    },
    {
      name: 'Full-Stack Web Platform',
      description: 'Production web application with authentication, real-time features, and cloud deployment',
      tech: ['Next.js', 'FastAPI', 'PostgreSQL', 'Docker', 'AWS']
    },
    {
      name: 'RAG Document System',
      description: 'Intelligent document retrieval and question-answering system',
      tech: ['LangChain', 'Vector Databases', 'OpenAI', 'Python']
    }
  ]
};

// =============================================================================
// Education
// =============================================================================

export const EDUCATION = {
  $schema: './schemas/education.schema.json',
  primary: {
    degree: 'Bachelor of Science Degree in Computer Science',
    institution: 'California State University, Sacramento',
    graduation: '2025 Winter Graduate',
    logo_path: '/resources/school_logo.png'
  },
  certifications: []
};

// =============================================================================
// Contact Information
// =============================================================================

export const CONTACT = {
  $schema: './schemas/contact.schema.json',
  email: 'hello@example.com',
  social: {
    github: {
      url: 'https://github.com/bassnp',
      display: 'bassnp'
    },
    mail: {
      url: 'mailto:hello@example.com',
      display: 'Email'
    }
  },
  repo: {
    url: 'https://github.com/bassnp/res_web',
    display: 'View Source Code'
  }
};

// =============================================================================
// Assets
// =============================================================================

export const ASSETS = {
  $schema: './schemas/assets.schema.json',
  portrait: '/resources/portrait.jpg',
  school_logo: '/resources/school_logo.png',
  resume_pdf: {
    path: '/resources/SSR_TSRPT.pdf',
    thumbnail: '/resources/SSR_TSRPT_thumb.jpg',
    label: 'PDF Formatted Resume'
  },
  personal_collage: {
    folder: '/resources/personal_collage/',
    manifest: '/resources/collage_manifest.json'
  },
  project_images_base: '/resources/project_images/',
  timeline_images_base: '/resources/timeline_images/'
};

// =============================================================================
// Site Metadata
// =============================================================================

export const SITE_METADATA = {
  $schema: './schemas/site_metadata.schema.json',
  site: {
    title: 'Portfolio | Software Engineer',
    description: 'Personal resume and portfolio showcasing projects and work experience',
    og_image: '/resources/og-image.png'
  },
  theme: {
    default: 'system'
  },
  deployment: {
    backend_port: 8000,
    frontend_port: 3003,
    api_base_url_dev: 'http://localhost:8000',
    frontend_url_dev: 'http://localhost:3003',
    cors_origins: ['http://localhost:3003']
  },
  repository: {
    name: 'res_web',
    image_name: 'res_web',
    image_tag: 'latest',
    maintainer: 'res_web',
    source: 'https://github.com/bassnp/res_web'
  }
};

// =============================================================================
// Experience Timeline
// =============================================================================

export const EXPERIENCE = {
  $schema: './schemas/experience.schema.json',
  timeline: [
    {
      id: 1,
      title: 'Software Engineer',
      company: 'Tech Innovation Corp',
      period: 'December 2025',
      description: 'Leading full-stack development initiatives with modern web technologies and AI integration.',
      tags: ['React', 'Node.js', 'AWS', 'TypeScript'],
      color: 'burnt-peach',
      showcase_folder: 'showcase1'
    }
  ]
};

// =============================================================================
// Convenience Exports
// =============================================================================

// API Configuration
export const API_BASE_URL = SITE_METADATA.deployment.api_base_url_dev;

// Hero Section
export const HERO_TEXT = {
  left: IDENTITY.hero.animation_left,
  right: IDENTITY.hero.animation_right,
};

// Skills for display
export const PRIMARY_SKILLS = SKILLS.display_categories.primary.skills;
export const DEVOPS_SKILLS = SKILLS.display_categories.devops.skills;

// Projects for display
export const FEATURED_PROJECTS = PROJECTS.featured;

// Education for display
export const PRIMARY_EDUCATION = EDUCATION.primary;

// Contact for display
export const EMAIL = CONTACT.email;
export const GITHUB_URL = CONTACT.social.github.url;
export const GITHUB_USERNAME = CONTACT.social.github.display;
export const REPO_URL = CONTACT.repo.url;

// Portrait
export const PORTRAIT_PATH = ASSETS.portrait;
export const PORTRAIT_ALT = IDENTITY.portrait.alt;

// Bio
export const BIO_TLDR = IDENTITY.bio.tldr;
export const BIO_FULL = IDENTITY.bio.full;
